version: '3.9'

services:
  app:
    build: .
    container_name: app
    restart: always
    environment:
      CONSOLE_LOGS: "true"
      API_URL: "https://candidate-testing.com"
      API_USER_EMAIL: "ahsoka.tano@royal-apps.io"
      API_USER_PASSWORD: "Kryze4President"
    expose:
      - "9000"

  web:
    image: nginx:latest
    container_name: web
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
