version: '3.9'

services:
  app:
    build: .
    container_name: app
    restart: always
    environment:
      CONSOLE_LOGS: "true"
    expose:
      - "9000"

  web:
    image: nginx:latest
    container_name: web
    restart: always
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
